import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(scriptDir, "..", "..");
const publicDir = path.join(rootDir, "public");
const outDir = path.join(rootDir, "dist");

const staticPriority = new Map([
  ["", 1.0],
  ["news", 0.8],
  ["events", 0.8],
  ["report", 0.8],
]);

const walkHtmlFiles = async (directory) => {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await walkHtmlFiles(fullPath)));
      continue;
    }

    if (entry.name.endsWith(".html")) {
      files.push(fullPath);
    }
  }

  return files;
};

const toRoutePath = (absolutePath) => {
  const relativePath = path.relative(outDir, absolutePath).replace(/\\/g, "/");

  if (relativePath === "index.html") {
    return "";
  }

  if (relativePath.endsWith("/index.html")) {
    return relativePath.slice(0, -"/index.html".length);
  }

  if (relativePath.endsWith(".html")) {
    return relativePath.slice(0, -".html".length);
  }

  return null;
};

const getPriority = (route) => {
  if (staticPriority.has(route)) {
    return staticPriority.get(route);
  }

  if (route.startsWith("data/")) {
    return 0.7;
  }

  return 0.6;
};

const escapeXml = (value) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&apos;");

const resolveBaseUrl = async () => {
  if (process.env.SITE_URL) {
    return process.env.SITE_URL.replace(/\/$/, "");
  }

  try {
    const domain = (await fs.readFile(path.join(publicDir, "CNAME"), "utf8")).trim();

    if (domain) {
      return `https://${domain}`;
    }
  } catch {
    // Fall through to default.
  }

  return "https://www.civictechsaitama.com";
};

const generateSitemap = async () => {
  const baseUrl = await resolveBaseUrl();
  const htmlFiles = await walkHtmlFiles(outDir);
  const routes = new Map();

  for (const filePath of htmlFiles) {
    const route = toRoutePath(filePath);

    if (route === null || route.startsWith("_astro/")) {
      continue;
    }

    const stats = await fs.stat(filePath);
    routes.set(route, {
      route,
      lastmod: stats.mtime.toISOString().slice(0, 10),
      priority: getPriority(route),
    });
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${[
    ...routes.values(),
  ]
    .sort((left, right) => left.route.localeCompare(right.route))
    .map(({ route, lastmod, priority }) => {
      const pathname = route ? `/${route}` : "";
      return `  <url>\n    <loc>${escapeXml(`${baseUrl}${pathname}`)}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <priority>${priority.toFixed(1)}</priority>\n  </url>`;
    })
    .join("\n")}\n</urlset>\n`;

  await fs.writeFile(path.join(outDir, "sitemap.xml"), xml, "utf8");

  const robots = `# Generated by Astro build\nUser-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /*.json$\n\nSitemap: ${baseUrl}/sitemap.xml\n`;
  await fs.writeFile(path.join(outDir, "robots.txt"), robots, "utf8");
};

await generateSitemap();
